### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by alanorth** [ilri/DAGRIS#79]
[Drupal is licensed](https://www.drupal.org/licensing/faq) under the GPLv2 or later, and ILRI's preference is GPLv3 so the latter is probably the best choice.

Add a `LICENSE` file with the verbatim text of the GPLv3 as well as a note in the readme. Thanks, @tsega. ;)

**Comment by tsega** [comment]
@alanorth thanks for the reminder. The GPL v3 License file and the note in the readme have been added.

**Comment by alanorth** [comment]
:+1: Thanks, we're starting to push for GitHub compliance for ILRI source code etc, so I started looking at our old repositories, checking for licenses, readmes, descriptions, etc.
